### ISSUE TITLE
Missing character in Response 

### ISSUE THREAD

**Issue by compocas** [socialtables/saml-protocol#17]
Hello,
Seems that in the `lib/response-construction.js` file,
in line 231, It should be `saml:AuthnContext` instead of `saml:AuthnContex`, it's missing the tailing `t` character. 
Validating on an online platform wouldn't pass without correcting it...

**Comment by delboy1978uk** [comment]
We have this issue too

**Comment by delboy1978uk** [comment]
Fixed with this PR -  https://github.com/socialtables/saml-protocol/pull/22

**Comment by AndrewCsontos** [comment]
Fixed in 0.4.0. @delboy1978uk  - thanks for the PR.

**Comment by delboy1978uk** [comment]
Thanks for the fast response! Cheers!
